// Responsive artwork manifest, generated by scripts/optimize-images.py:
// name -> emitted variant widths + the intrinsic size of the largest variant
// (used so the browser can reserve space before the image loads).
import IMAGES from "./images.json";

export { IMAGES };

export const imagePath = (file) => `${process.env.PUBLIC_URL}/images/${file}`;
