// Single source of truth for the responsive artwork generated by
// scripts/optimize-images.py. `widths` are the emitted variant widths;
// width/height are the intrinsic size of the largest variant (used so the
// browser can reserve space before the image loads and avoid layout shift).
export const IMAGES = {
  illustration: { widths: [480, 800, 1400], width: 1400, height: 1447 },
  "hand-drawn": { widths: [480, 900, 1400], width: 1400, height: 1340 },
  project1: { widths: [300, 500], width: 500, height: 955 },
  project2: { widths: [560, 1128], width: 1128, height: 965 },
  project3: { widths: [600, 1000, 1500], width: 1500, height: 914 },
  gravestone: { widths: [600, 1200], width: 1200, height: 800 },
  "core-tools": { widths: [520, 1040], width: 1040, height: 148 },
};

export const imagePath = (file) => `${process.env.PUBLIC_URL}/images/${file}`;
